# Generated by Django 6.0.7 on 2026-07-10 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beans', models.CharField(max_length=100)),
                ('method', models.CharField(choices=[('Pour Over', 'Pour Over'), ('French Press', 'French Press'), ('Espresso', 'Espresso'), ('Aeropress', 'Aeropress')], max_length=30)),
                ('coffee_grams', models.PositiveIntegerField()),
                ('water_grams', models.PositiveIntegerField()),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('tasting_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
