# Generated by Django 6.0.7 on 2026-07-12 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brew',
            name='tasting_notes',
            field=models.TextField(),
        ),
    ]
